// <auto-generated />
using System;
using System.Collections.Generic;
using Bim.Cvc.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bim.Cvc.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BimCvcDbContext))]
    partial class BimCvcDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bim.Cvc.Domain.CvcObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<Guid>>("ConnectedObjectIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("connected_object_ids");

                    b.Property<double?>("DebitM3h")
                        .HasColumnType("double precision");

                    b.Property<double?>("DiameterMm")
                        .HasColumnType("double precision");

                    b.Property<Guid>("DrawingId")
                        .HasColumnType("uuid");

                    b.Property<double?>("HeightMm")
                        .HasColumnType("double precision");

                    b.Property<Guid>("LayerId")
                        .HasColumnType("uuid");

                    b.Property<double?>("PressionPa")
                        .HasColumnType("double precision");

                    b.Property<double>("RotationRad")
                        .HasColumnType("double precision");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<double?>("VitesseMs")
                        .HasColumnType("double precision");

                    b.Property<double?>("WidthMm")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DrawingId");

                    b.HasIndex("LayerId");

                    b.ToTable("cvc_objects", (string)null);
                });

            modelBuilder.Entity("Bim.Cvc.Domain.Drawing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Calibration")
                        .HasColumnType("jsonb")
                        .HasColumnName("calibration");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("NbPages")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VectorEntities")
                        .HasColumnType("jsonb")
                        .HasColumnName("vector_entities");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("drawings", (string)null);
                });

            modelBuilder.Entity("Bim.Cvc.Domain.Layer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("DrawingId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DrawingId");

                    b.ToTable("layers", (string)null);
                });

            modelBuilder.Entity("Bim.Cvc.Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Bim.Cvc.Domain.CvcObject", b =>
                {
                    b.HasOne("Bim.Cvc.Domain.Drawing", null)
                        .WithMany()
                        .HasForeignKey("DrawingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bim.Cvc.Domain.Layer", null)
                        .WithMany()
                        .HasForeignKey("LayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Bim.Cvc.Domain.Point2D", "End", b1 =>
                        {
                            b1.Property<Guid>("CvcObjectId")
                                .HasColumnType("uuid");

                            b1.Property<double>("X")
                                .HasColumnType("double precision")
                                .HasColumnName("end_x");

                            b1.Property<double>("Y")
                                .HasColumnType("double precision")
                                .HasColumnName("end_y");

                            b1.HasKey("CvcObjectId");

                            b1.ToTable("cvc_objects");

                            b1.WithOwner()
                                .HasForeignKey("CvcObjectId");
                        });

                    b.OwnsOne("Bim.Cvc.Domain.Point2D", "Position", b1 =>
                        {
                            b1.Property<Guid>("CvcObjectId")
                                .HasColumnType("uuid");

                            b1.Property<double>("X")
                                .HasColumnType("double precision")
                                .HasColumnName("position_x");

                            b1.Property<double>("Y")
                                .HasColumnType("double precision")
                                .HasColumnName("position_y");

                            b1.HasKey("CvcObjectId");

                            b1.ToTable("cvc_objects");

                            b1.WithOwner()
                                .HasForeignKey("CvcObjectId");
                        });

                    b.OwnsOne("Bim.Cvc.Domain.Point2D", "Start", b1 =>
                        {
                            b1.Property<Guid>("CvcObjectId")
                                .HasColumnType("uuid");

                            b1.Property<double>("X")
                                .HasColumnType("double precision")
                                .HasColumnName("start_x");

                            b1.Property<double>("Y")
                                .HasColumnType("double precision")
                                .HasColumnName("start_y");

                            b1.HasKey("CvcObjectId");

                            b1.ToTable("cvc_objects");

                            b1.WithOwner()
                                .HasForeignKey("CvcObjectId");
                        });

                    b.Navigation("End");

                    b.Navigation("Position");

                    b.Navigation("Start");
                });

            modelBuilder.Entity("Bim.Cvc.Domain.Drawing", b =>
                {
                    b.HasOne("Bim.Cvc.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bim.Cvc.Domain.Layer", b =>
                {
                    b.HasOne("Bim.Cvc.Domain.Drawing", null)
                        .WithMany()
                        .HasForeignKey("DrawingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
