<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>BimMep.Core.Ifc</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core.Geometry\Core.Geometry.csproj" />
    <ProjectReference Include="..\Core.Bim\Core.Bim.csproj" />
    <ProjectReference Include="..\Core.Mep\Core.Mep.csproj" />
  </ItemGroup>

</Project>
