// <auto-generated />
using System;
using BimMep.Services.ProjectManagement;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BimMep.Services.ProjectManagement.Migrations
{
    [DbContext(typeof(BimMepDbContext))]
    [Migration("20260903200930_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BimMep.Services.ProjectManagement.Entities.BimElementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Polygon>("Bbox")
                        .HasColumnType("geometry(PolygonZ,0)")
                        .HasColumnName("bbox");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("FamilyTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_type_id");

                    b.Property<string>("IfcGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ifc_guid");

                    b.Property<Guid?>("LevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("level_id");

                    b.Property<short>("Lod")
                        .HasColumnType("smallint")
                        .HasColumnName("lod");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters");

                    b.Property<Point>("Placement")
                        .HasColumnType("geometry(PointZ,0)")
                        .HasColumnName("placement");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("revision_number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_bim_elements");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_bim_elements_created_by");

                    b.HasIndex("FamilyTypeId")
                        .HasDatabaseName("ix_bim_elements_family_type_id");

                    b.HasIndex("IfcGuid")
                        .IsUnique()
                        .HasDatabaseName("ix_bim_elements_ifc_guid");

                    b.HasIndex("LevelId")
                        .HasDatabaseName("ix_bim_elements_level_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_bim_elements_project_id");

                    b.ToTable("bim_elements", (string)null);
                });

            modelBuilder.Entity("BimMep.Services.ProjectManagement.Entities.ClashEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClashType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clash_type");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<Guid>("ElementAId")
                        .HasColumnType("uuid")
                        .HasColumnName("element_a_id");

                    b.Property<Guid>("ElementBId")
                        .HasColumnType("uuid")
                        .HasColumnName("element_b_id");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry(PointZ,0)")
                        .HasColumnName("location");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SuggestedResolutionJson")
                        .HasColumnType("text")
                        .HasColumnName("suggested_resolution_json");

                    b.HasKey("Id")
                        .HasName("pk_clashes");

                    b.HasIndex("ElementAId")
                        .HasDatabaseName("ix_clashes_element_a_id");

                    b.HasIndex("ElementBId")
                        .HasDatabaseName("ix_clashes_element_b_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_clashes_project_id");

                    b.ToTable("clashes", (string)null);
                });

            modelBuilder.Entity("BimMep.Services.ProjectManagement.Entities.FamilyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_families");

                    b.ToTable("families", (string)null);
                });

            modelBuilder.Entity("BimMep.Services.ProjectManagement.Entities.FamilyTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters");

                    b.HasKey("Id")
                        .HasName("pk_family_types");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_family_types_family_id");

                    b.ToTable("family_types", (string)null);
                });

            modelBuilder.Entity("BimMep.Services.ProjectManagement.Entities.LevelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("ElevationM")
                        .HasColumnType("double precision")
                        .HasColumnName("elevation_m");

                    b.Property<double>("HeightM")
                        .HasColumnType("double precision")
                        .HasColumnName("height_m");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_levels");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_levels_project_id");

                    b.ToTable("levels", (string)null);
                });

            modelBuilder.Entity("BimMep.Services.ProjectManagement.Entities.MepConnectorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ConnectedToId")
                        .HasColumnType("uuid")
                        .HasColumnName("connected_to_id");

                    b.Property<string>("ConnectorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("connector_type");

                    b.Property<double>("DirectionX")
                        .HasColumnType("double precision")
                        .HasColumnName("direction_x");

                    b.Property<double>("DirectionY")
                        .HasColumnType("double precision")
                        .HasColumnName("direction_y");

                    b.Property<double>("DirectionZ")
                        .HasColumnType("double precision")
                        .HasColumnName("direction_z");

                    b.Property<Guid>("ElementId")
                        .HasColumnType("uuid")
                        .HasColumnName("element_id");

                    b.Property<Point>("Position")
                        .IsRequired()
                        .HasColumnType("geometry(PointZ,0)")
                        .HasColumnName("position");

                    b.Property<double>("SizePrimary")
                        .HasColumnType("double precision")
                        .HasColumnName("size_primary");

                    b.Property<double>("SizeSecondary")
                        .HasColumnType("double precision")
                        .HasColumnName("size_secondary");

                    b.Property<string>("SystemClassification")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("system_classification");

                    b.Property<Guid?>("SystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("system_id");

                    b.HasKey("Id")
                        .HasName("pk_mep_connectors");

                    b.HasIndex("ConnectedToId")
                        .HasDatabaseName("ix_mep_connectors_connected_to_id");

                    b.HasIndex("ElementId")
                        .HasDatabaseName("ix_mep_connectors_element_id");

                    b.HasIndex("SystemId")
                        .HasDatabaseName("ix_mep_connectors_system_id");

                    b.ToTable("mep_connectors", (string)null);
                });

            modelBuilder.Entity("BimMep.Services.ProjectManagement.Entities.MepNetworkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("DesignFlow")
                        .HasColumnType("double precision")
                        .HasColumnName("design_flow");

                    b.Property<double?>("DesignPressureLoss")
                        .HasColumnType("double precision")
                        .HasColumnName("design_pressure_loss");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_mep_networks");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_mep_networks_project_id");

                    b.ToTable("mep_networks", (string)null);
                });

            modelBuilder.Entity("BimMep.Services.ProjectManagement.Entities.OrganizationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("BimMep.Services.ProjectManagement.Entities.ProjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<short>("LodTarget")
                        .HasColumnType("smallint")
                        .HasColumnName("lod_target");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phase");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_projects_organization_id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("BimMep.Services.ProjectManagement.Entities.RoomEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("AreaM2")
                        .HasColumnType("double precision")
                        .HasColumnName("area_m2");

                    b.Property<Polygon>("Boundary")
                        .IsRequired()
                        .HasColumnType("geometry(PolygonZ,0)")
                        .HasColumnName("boundary");

                    b.Property<double?>("CoolingLoadW")
                        .HasColumnType("double precision")
                        .HasColumnName("cooling_load_w");

                    b.Property<double?>("HeatingLoadW")
                        .HasColumnType("double precision")
                        .HasColumnName("heating_load_w");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("level_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<double?>("VolumeM3")
                        .HasColumnType("double precision")
                        .HasColumnName("volume_m3");

                    b.HasKey("Id")
                        .HasName("pk_rooms");

                    b.HasIndex("LevelId")
                        .HasDatabaseName("ix_rooms_level_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_rooms_project_id");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("BimMep.Services.ProjectManagement.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BimMep.Services.ProjectManagement.Entities.BimElementEntity", b =>
                {
                    b.HasOne("BimMep.Services.ProjectManagement.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bim_elements_users_created_by");

                    b.HasOne("BimMep.Services.ProjectManagement.Entities.FamilyTypeEntity", "FamilyType")
                        .WithMany()
                        .HasForeignKey("FamilyTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_bim_elements_family_types_family_type_id");

                    b.HasOne("BimMep.Services.ProjectManagement.Entities.LevelEntity", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_bim_elements_levels_level_id");

                    b.HasOne("BimMep.Services.ProjectManagement.Entities.ProjectEntity", "Project")
                        .WithMany("Elements")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bim_elements_projects_project_id");

                    b.Navigation("FamilyType");

                    b.Navigation("Level");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BimMep.Services.ProjectManagement.Entities.ClashEntity", b =>
                {
                    b.HasOne("BimMep.Services.ProjectManagement.Entities.BimElementEntity", "ElementA")
                        .WithMany()
                        .HasForeignKey("ElementAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clashes_bim_elements_element_a_id");

                    b.HasOne("BimMep.Services.ProjectManagement.Entities.BimElementEntity", "ElementB")
                        .WithMany()
                        .HasForeignKey("ElementBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clashes_bim_elements_element_b_id");

                    b.HasOne("BimMep.Services.ProjectManagement.Entities.ProjectEntity", "Project")
                        .WithMany("Clashes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clashes_projects_project_id");

                    b.Navigation("ElementA");

                    b.Navigation("ElementB");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BimMep.Services.ProjectManagement.Entities.FamilyTypeEntity", b =>
                {
                    b.HasOne("BimMep.Services.ProjectManagement.Entities.FamilyEntity", "Family")
                        .WithMany("Types")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_family_types_families_family_id");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("BimMep.Services.ProjectManagement.Entities.LevelEntity", b =>
                {
                    b.HasOne("BimMep.Services.ProjectManagement.Entities.ProjectEntity", "Project")
                        .WithMany("Levels")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_levels_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BimMep.Services.ProjectManagement.Entities.MepConnectorEntity", b =>
                {
                    b.HasOne("BimMep.Services.ProjectManagement.Entities.MepConnectorEntity", "ConnectedTo")
                        .WithMany()
                        .HasForeignKey("ConnectedToId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_mep_connectors_mep_connectors_connected_to_id");

                    b.HasOne("BimMep.Services.ProjectManagement.Entities.BimElementEntity", "Element")
                        .WithMany("Connectors")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mep_connectors_bim_elements_element_id");

                    b.HasOne("BimMep.Services.ProjectManagement.Entities.MepNetworkEntity", "Network")
                        .WithMany("Connectors")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_mep_connectors_mep_networks_system_id");

                    b.Navigation("ConnectedTo");

                    b.Navigation("Element");

                    b.Navigation("Network");
                });

            modelBuilder.Entity("BimMep.Services.ProjectManagement.Entities.MepNetworkEntity", b =>
                {
                    b.HasOne("BimMep.Services.ProjectManagement.Entities.ProjectEntity", "Project")
                        .WithMany("Networks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mep_networks_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BimMep.Services.ProjectManagement.Entities.ProjectEntity", b =>
                {
                    b.HasOne("BimMep.Services.ProjectManagement.Entities.OrganizationEntity", "Organization")
                        .WithMany("Projects")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_projects_organizations_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("BimMep.Services.ProjectManagement.Entities.RoomEntity", b =>
                {
                    b.HasOne("BimMep.Services.ProjectManagement.Entities.LevelEntity", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rooms_levels_level_id");

                    b.HasOne("BimMep.Services.ProjectManagement.Entities.ProjectEntity", "Project")
                        .WithMany("Rooms")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rooms_projects_project_id");

                    b.Navigation("Level");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BimMep.Services.ProjectManagement.Entities.BimElementEntity", b =>
                {
                    b.Navigation("Connectors");
                });

            modelBuilder.Entity("BimMep.Services.ProjectManagement.Entities.FamilyEntity", b =>
                {
                    b.Navigation("Types");
                });

            modelBuilder.Entity("BimMep.Services.ProjectManagement.Entities.MepNetworkEntity", b =>
                {
                    b.Navigation("Connectors");
                });

            modelBuilder.Entity("BimMep.Services.ProjectManagement.Entities.OrganizationEntity", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("BimMep.Services.ProjectManagement.Entities.ProjectEntity", b =>
                {
                    b.Navigation("Clashes");

                    b.Navigation("Elements");

                    b.Navigation("Levels");

                    b.Navigation("Networks");

                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
