<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bim.Cvc.Domain\Bim.Cvc.Domain.csproj" />
    <ProjectReference Include="..\Bim.Cvc.Application\Bim.Cvc.Application.csproj" />
    <ProjectReference Include="..\Bim.Cvc.Infrastructure\Bim.Cvc.Infrastructure.csproj" />
  </ItemGroup>

</Project>
